project_name: juno
before:
  hooks:
    - go mod tidy
    - go generate ./...
release:
  draft: true
  prerelease: auto
  mode: append
  header: |
    ## Some title ({{ .Date }})

    Welcome to this new release!

  footer: |
    ## Thanks!

    Those were the changes on {{ .Tag }}!

  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/juno/juno.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "wojciechos/juno-fork:{{ .Version }}"
      - "wojciechos/juno-fork:latest"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: goreleaser.Dockerfile
    image_templates:
      - "wojciechos/juno-fork:{{ .Version }}"
      - "wojciechos/juno-fork:latest"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: wojciechos/juno-fork:{{ .Version }}
    image_templates:
      - wojciechos/juno-fork:{{ .Version }}-amd64
      - wojciechos/juno-fork:{{ .Version }}-arm64v8
  - name_template: wojciechos/juno-fork:latest
    image_templates:
      - wojciechos/juno-fork:latest-amd64
      - wojciechos/juno-fork:latest-arm64v8
      
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
