name: Retag Docker Images on Release Publish

on:
  release:
    types: [published]

jobs:
  retag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Retag and push Docker images
      run: |
        VERSION_TAG=${{ github.event.release.tag_name }}
        DRAFT_IMAGE="wojciechos/juno-fork:${VERSION_TAG}-draft"
        OFFICIAL_IMAGE="wojciechos/juno-fork-official:${VERSION_TAG}"
        docker buildx imagetools create -t ${OFFICIAL_IMAGE} ${DRAFT_IMAGE}
        docker buildx imagetools push ${OFFICIAL_IMAGE}




